### PR TITLE
AUR Stuff

### PR DESCRIPTION
**Pull request by GizzyUwU**
AUR PKGBUILD and .SRCINFO

### CODE REVIEW

**Comment by oxmc** [comment]
@GizzyUwU Are you able to add the arm arch (armhf), as the build-app.js file does support that arch (armv7l)

**Comment by GizzyUwU** [comment]
@oxmc pkg relys on appimage to install as there is no appimage for armhf it doesnt build for that version

**Comment by oxmc** [comment]
@GizzyUwU So does that mean that there will only be a 64bit version of the app in appimage form?

**Comment by GizzyUwU** [comment]
there can be an armhf version just need a appimage release for it

**Comment by oxmc** [comment]
@GizzyUwU Does that mean we have to make a port of appimage to support the armhf one?

**Comment by GizzyUwU** [comment]
Yeah

**Comment by oxmc** [comment]
If electron builder can set custom sources for the appimage i'm more than happy to revisit the armhf idea later, as for now i'll approve the new files

**Comment by GizzyUwU** [comment]
:+1:

**Pull request merged**
